# Generated by Django 5.0.3 on 2024-04-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_description_alter_location_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprating',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.trip'),
        ),
    ]
