# Generated by Django 5.0.3 on 2024-05-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_trip_location_remove_recommendation_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_rate',
            field=models.FloatField(blank=True, default=0.0, max_length=5.0, null=True),
        ),
    ]
