# Generated by Django 5.0.3 on 2024-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_rate',
        ),
        migrations.AddField(
            model_name='trip',
            name='visitor_rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
