# Generated by Django 5.0.3 on 2024-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_trip_information_trip_historical_significance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
